server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
        - id: vehicle-service
          uri: http://localhost:4000
          predicates:
            - Path=/api/vehicles/**
        - id: parking-space-service
          uri: lb://PARKING-SPACE-SERVICE
          predicates:
            - Path=/api/parking/**
        - id: payment-service
          uri: http://localhost:5000
          predicates:
            - Path=/api/payments/**

      discovery:
        locator:
          enabled: true

      server:
        webflux:
           default-filters:
            - AddRequestHeader=Authorization, "#{request.headers['Authorization']}"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

