server:
  port: 8081
  servlet:
    context-path: /user-service

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/spms_user_db
    username: root
    password: Shen@1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/