server:
  port: 8082
  servlet:
    context-path: /parking-service

spring:
  application:
    name: parking-service
  datasource:
    url: jdbc:mysql://localhost:3306/spms_parking_zone_db
    username: root
    password: Ijse@1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
